### PR TITLE
add net-dns/getdns package

### PR DESCRIPTION
**Pull request by CaseOf**
I was looking for a dns daemon that offers dns over tls support with certificate check. I found stubby, but as there were no ebuild available, I made one. I thought it was a good idea to share it.

### CODE REVIEW

**Comment by csmk** [comment]
I'm very interested in this package, do you mind if I reopen the PR and merge your contribution?

**Comment by CaseOf** [comment]
No problem, you can reopen it.
Also, I have to tell you that I made an overlay for it and added it to overlays list.
It contains a newer version and improved ebuild.
Don't hesitate to ask if you want more infos.

**Comment by csmk** [comment]
> Also, I have to tell you that I made an overlay for it and added it to overlays list.
> It contains a newer version and improved ebuild.

In that case, let's reduce the redundancy and keep in this way.

> Don't hesitate to ask if you want more infos or if you have any suggestion.

Thanks. I'll check it in another time and see if I can contribute on something.

**Comment by CaseOf** [comment]
It seems that I'm able to soon have it on portage tree. It would be great.

**Comment by csmk** [comment]
Yeah, it's nice to hear that. I'll check out it later.

**Comment by CaseOf** [comment]
https://packages.gentoo.org/packages/net-dns/getdns

**Pull request closed without merging**
